apiVersion: v1
kind: ServiceAccount
metadata:
  name: support-desk-sa
  namespace: support-desk
  annotations:
    eks.amazonaws.com/role-arn:  "arn:aws:iam::124990256338:role/support-desk-prod-app-pod-role"
